labels:
  - name: "sync-up"
    color: "beff6e"
    description: "Issue should be shared to the sync-up board"
  - name: "Goals"
    color: "889b70"
    description: "Issue related to Goals"
  - name: "gbp"
    color: "ff6e6e"
    description: "Issue related to Global Business Platform"
  - name: "cpp"
    color: "6eff6e"
    description: "Issue related to Cross Product Promotions"
milestones:
  - title: "Q1"
    description: "Q1 Goals"
    dueon: "2023-03-31T23:59:59Z"
  - title: "Q2"
    description: "Q2 Goals"
    dueon: "2023-03-30T23:59:59Z"
  - title: "Q3"
    description: "Q3 Goals"
    dueon: "2023-03-30T23:59:59Z"
  - title: "Q4"
    description: "Q4 Goals"
    dueon: "2023-03-31T23:59:59Z"
  