name: "Sediment Test"
on:
  workflow_dispatch:


jobs:
  sediment:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Sediment"
        uses: ./
        with:
          configfile: "./config.yml"
          token: ${{ secrets.GITHUB_TOKEN }}